CREATE USER ORCLSTUDY IDENTIFIED BY oracle;

GRANT CREATE TABLE TO ORCLSTUDY;
GRANT CONNECT,RESOURCE TO ORCLSTUDY;

REVOKE CONNECT FROM ORCLSTUDY;

alter user ORCLSTUDY identified by "orcl";

DROP USER ORCLSTUDY CASCADE;

CREATE TABLE EMP_DDL (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
    );
DESC emp_ddl;

ALTER TABLE EMP_DDL RENAME TO EMP_ALTAR;
SELECT * FROM emp_altar;

ALTER TABLE EMP_ALTAR ADD HP VARCHAR2(20);
SELECT * FROM emp_altar;

ALTER TABLE EMP_ALTAR RENAME column HP TO TEL;

ALTER TABLE EMP_ALTAR MODIFY EMPNO NUMBER(5);

ALTER TABLE emp_altar DROP COLUMN TEL;

DROP TABLE emp_altar;
desc emp_altar;

CREATE INDEX IDX_EMP_SAL ON emp(SAL);

SELECT * FROM USER_IND_COLUMNS
WHERE table_name = 'EMP';

DROP INDEX IDX_EMP_SAL;

GRANT CREATE VIEW TO scott;
